// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads capturados na landing page KMR, com filtro opcional por status.",
  inputSchema: {
    status: z.string().optional().describe("Filtrar por status (ex.: novo, qualificado, agendado)."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb(ctx).from("leads").select("id,name,email,phone,company,interest,status,scheduled_at,created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { leads: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-contracts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contracts_default = defineTool2({
  name: "list_contracts",
  title: "Listar contratos auditados",
  description: "Lista contratos do m\xF3dulo de Auditoria KMR com filtros opcionais por status e garantidora.",
  inputSchema: {
    audit_status: z2.string().optional().describe("Ex.: pendente, aprovado, reprovado."),
    garantidora: z2.string().optional(),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ audit_status, garantidora, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb2(ctx).from("audit_contracts").select("id,imoview_number,garantidora,empresa,locatario_nome,locador_nome,endereco_imovel,valor_aluguel,data_inicio,data_fim,audit_status,status_contrato,analyst_name,created_at").order("created_at", { ascending: false }).limit(limit);
    if (audit_status) q = q.eq("audit_status", audit_status);
    if (garantidora) q = q.eq("garantidora", garantidora);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { contracts: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-sinistros.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_sinistros_default = defineTool3({
  name: "list_sinistros",
  title: "Listar sinistros",
  description: "Lista sinistros (avisos de desocupa\xE7\xE3o) KMR com filtro opcional por status.",
  inputSchema: {
    status: z3.string().optional(),
    empresa: z3.string().optional(),
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, empresa, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb3(ctx).from("sinistros").select("id,inquilino_nome,inquilino_cpf,codigo_contrato,status_imovel,motivo_desocupacao,data_entrega_chaves,status,empresa,created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (empresa) q = q.eq("empresa", empresa);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { sinistros: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-contract.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_contract_default = defineTool4({
  name: "get_contract",
  title: "Detalhar contrato",
  description: "Retorna dados completos de um contrato de auditoria KMR pelo id, incluindo checklist e dados extra\xEDdos do PDF.",
  inputSchema: { id: z4.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const client = sb4(ctx);
    const [c, checklist, extracted] = await Promise.all([
      client.from("audit_contracts").select("*").eq("id", id).maybeSingle(),
      client.from("audit_checklist_items").select("*").eq("contract_id", id),
      client.from("audit_contract_extracted_data").select("*").eq("contract_id", id).maybeSingle()
    ]);
    if (c.error) return { content: [{ type: "text", text: c.error.message }], isError: true };
    if (!c.data) return { content: [{ type: "text", text: "Contrato n\xE3o encontrado" }], isError: true };
    const payload = { contract: c.data, checklist: checklist.data ?? [], extracted: extracted.data ?? null };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "odntzbmmepjfcusleefd";
var mcp_default = defineMcp({
  name: "kmr-mcp",
  title: "KMR \u2014 Garantia locat\xEDcia",
  version: "0.1.0",
  instructions: "Ferramentas KMR para consultar leads capturados, contratos do m\xF3dulo de Auditoria e sinistros (avisos de desocupa\xE7\xE3o). Todas as a\xE7\xF5es rodam como o usu\xE1rio conectado, respeitando as permiss\xF5es da plataforma.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, list_contracts_default, list_sinistros_default, get_contract_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
